/*
@
 This file contains the types constants
@
*/

export const FETCH_QUESTION_REQUEST = "FETCH_QUESTION_REQUEST ";
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS ";
export const FETCH_QUESTION_FAILURE = "FETCH_QUESTION_FAILURE ";

export const FETCH_NEXT_QUESTION_REQUEST = "FETCH_NEXT_QUESTION_REQUEST ";
export const FETCH_NEXT_QUESTION_SUCCESS = "FETCH_NEXT_QUESTION_SUCCESS ";
export const FETCH_NEXT_QUESTION_FAILURE = "FETCH_NEXT_QUESTION_FAILURE ";

export const FETCH_PARTITIONS_BY_RESPONSE_REQUEST =
  "FETCH_PARTITIONS_BY_RESPONSE_REQUEST ";
export const FETCH_PARTITIONS_BY_RESPONSE_FAILURE =
  "FETCH_PARTITIONS_BY_RESPONSE_FAILURE ";
export const FETCH_PARTITIONS_BY_RESPONSE_SUCCESS =
  "FETCH_PARTITIONS_BY_RESPONSE_SUCCESS ";

export const FETCH_ANSWERS_REQUEST = "FETCH_ANSWERS_REQUEST ";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS ";
export const FETCH_ANSWERS_FAILURE = "FETCH_ANSWERS_FAILURE ";

export const ADD_PARTICION = "ADD_PARTICION ";
export const SET_LOADING_TRUE = "SET_LODING_TRUE ";
export const SET_LOADING_FALSE = "SET_LODING_FALSE ";

export const SET_END_TRUE = "SET_END_TRUE ";
export const SET_END_FALSE = "SET_END_FALSE ";
export const ADD_SUGGESTION_PICK = "ADD_SUGGESTION_PICK ";

export const SAVE_PICKS_REQUEST = "SAVE_PICKS_REQUEST ";
export const SAVE_PICKS_SUCCESS = "SAVE_PICKS_SUCCESS ";
export const SAVE_PICKS_FAILURE = "SAVE_PICKS_FAILURE ";

export const GET_VOUCHER_REQUEST = "GET_VOUCHER_REQUEST ";
export const GET_VOUCHER_SUCCESS = "GET_VOUCHER_SUCCESS ";
export const GET_VOUCHER_FAILURE = "GET_VOUCHER_FAILURE ";
