/*
@
 This file contains the types constants
@
*/

export const SIGNIN_REQUEST = "SIGNIN_REQUEST ";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE ";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS ";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST ";
export const SIGNUP_ERROR = "SIGNUP_ERROR ";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS ";

export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST ";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS ";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE ";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST ";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE ";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS ";

export const DISCONNECT_THE_USER = "DISCONNECT_THE_USER ";
export const CONNECT_THE_USER = "CONNECT_THE_USER ";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST ";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS ";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE ";

export const VALIDATE_ACCOUNT_REQUEST = "VALIDATE_ACCOUNT_REQUEST ";
export const VALIDATE_ACCOUNT_SUCCESS = "VALIDATE_ACCOUNT_SUCCESS ";
export const VALIDATE_ACCOUNT_FAILURE = "VALIDATE_ACCOUNT_FAILURE ";
